import refagent
from pydantic.v1 import BaseModel, Field, PrivateAttr
from typing import Callable, List, Optional, Type
from langchain_core.output_parsers import PydanticOutputParser, JsonOutputParser

from langgraph.graph import MessagesState
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage, AIMessage, BaseMessage
from langchain_core.language_models import BaseChatModel
from langgraph.graph.state import CompiledStateGraph
from langgraph.graph import StateGraph, START, END
from langchain_core.tools import tool, BaseTool

import refagent.agents.refactrix.supported_refactorings as sup_ref
import refagent.agents.refactrix.tools as tools
import refagent.utils.tool_documentation as td


class FixPlanningStep(BaseModel):
    """An actionable step to improve the code-quality."""

    # step_number: int = Field(description="The ")
    reason: str = Field(description="The reason why this action should be applied.")
    final_code: str = Field(description="The improved, modified version of the source code.")
    execution_details: str = Field(description="Details about what needs to change. "
                                               "E.g. rename variable x->index, or "
                                               "move method `bark` to target class `Dog`")
    refactoring_type: sup_ref.SupportedRefactorings = Field(
        description="The type of change that is needed. "
        "Please refer to the Fowler catalog of refactorings and pick one.")
    file_path: str = Field(description="The path to the source code where the "
                                       "refactoring operation should be triggered.")



class FixRefactoringPlan(BaseModel):
    steps: List[FixPlanningStep] = Field(description="An ordered list of steps to carry out the plan")

# structured_llm = llm.with_structured_output(Joke)


class Planner(BaseModel):
    def run(self) -> FixRefactoringPlan:
        return FixRefactoringPlan(steps=[])

class FixPlanningComponent(Planner):
    issue_description: str = Field(description="problem description from code inspection")
    model: BaseChatModel = Field(description="model to use to generate the plan")
    source_file_path: str = Field(description="the file path to the starting source code.")
    source_code: str = Field(description="source code to work with")
    detail_steps: bool = Field(description="detail the execution steps", default=True)
    personalization_rules: List[str] = Field(description="a list of personalization rules "
                                                          "that the refactoring must conform to. "
                                                          "Generated by the personalization agent",
                                              default=[]
                                              )
    _ref_plan: Optional[FixRefactoringPlan] = PrivateAttr(default=None)
    _generation_count: int = PrivateAttr(default=0)
    _tools: dict[str, BaseTool] = PrivateAttr(default=tools.RefactoringToolProvider(ide_server=None).get())

    @property
    def generation_system_message(self) -> SystemMessage:
        parser = PydanticOutputParser(pydantic_object=FixRefactoringPlan)
        documentation_str = "\n".join([f"{k.value}: {v}" for k,v in sup_ref.documentation.items()])

        return SystemMessage( "You are an expert developer using a powerful IDE IntelliJ IDEA, "
                              "capable of performing refactorng, and fixing issues."
                              "Please generate a step by step plan of IDE refactoring actions to "
                              f"solve the following issue: {self.issue_description}. "
                              f"Please provide a plan ONLY to fix the issue. "
                              f"Assume that other action steps will be taken care of by the developer."
                              f"Make sure that your plan is actionable on the given code. "
                              f"Do not include generic steps in this plan. "
                              f"{parser.get_format_instructions()}"
                              f"Here is some documentation for each refactoring type: {documentation_str}")


    def try_parsing(self, response: BaseMessage) -> Optional[FixPlanningStep]:
        try:
            json_ = JsonOutputParser().parse(response.content)
            return FixPlanningStep(**json_['properties'])
        except:
            return None

    def compile(self) -> CompiledStateGraph:
        def generate_plan(messages: MessagesState):
            parser = PydanticOutputParser(pydantic_object=FixRefactoringPlan)
            self._generation_count += 1
            # Set up a parser + inject instructions into the prompt template.

            response = self.model.invoke(
                messages['messages']
            )
            self._ref_plan = parser.invoke(response)
            messages_ret = []
            if self._generation_count !=1 or not self.detail_steps:
                messages_ret += [response]

            return {'messages': messages_ret}

        def detail_plan_steps(messages: MessagesState):
            if not self.detail_steps:
                return # don't detail the steps.

            parser = PydanticOutputParser(pydantic_object=FixPlanningStep)

            for i, cur_step in enumerate(self._ref_plan.steps):
                old_exec_details = cur_step.execution_details
                cur_step.execution_details = "to be determined."
                previous_steps = self._ref_plan.steps[:i+1]
                step_messages = "\n".join([f"step {i}: {s.json()}" for i, s in enumerate(previous_steps)])
                tool = self._tools.get(cur_step.refactoring_type.value)
                if tool is not None:
                    tool_description = td.get_tool_documentation(tool)
                    api_call_text = (f"Please refer to this API documentation of {cur_step.refactoring_type.value} "
                                     f"to detail the `execution_details` field. THIS IS IMPORTANT. "
                                     f"MAKE SURE the API can be called with the information you provide.: \n"
                                     f"{tool_description}\n")
                else:
                    api_call_text = ""

                messages_ = [
                    SystemMessage(f"You are a expert developer who adds details to an existing refactoring plan."),
                    HumanMessage(self.source_code),
                    AIMessage(f"Here are the steps in the refactoring plan: {step_messages}"),
                    HumanMessage(f"Please critique the last step, and improve it: {cur_step}. "
                                 f"{api_call_text}"
                                 f"Answer the following question: "
                                 f"Are there any missing details in the code? If yes, fill them out. "
                                 f"{parser.get_format_instructions()}")
                ]
                response = self.model.invoke(messages_)
                try:
                    new_step = parser.invoke(response)
                except:
                    print("Failed to parse the object :/.")
                    new_step = self.try_parsing(response)

                if new_step!=None:
                    self._ref_plan.steps[i] = new_step
                else:
                    cur_step.execution_details = old_exec_details # revert back the execution details

            return {'messages': [AIMessage(content=f"Here's the plan: \n{self._ref_plan.json()}")]}


        workflow = StateGraph(MessagesState)
        workflow.add_node("generate_fix_plan", generate_plan)
        workflow.add_node("detail_fix_plan", detail_plan_steps)

        workflow.add_edge(START, "generate_fix_plan")
        # On the first generation, add more details to the plan.
        workflow.add_conditional_edges("generate_fix_plan",
                                       lambda messages: self._generation_count == 1,
                                       {True: "detail_fix_plan", False: END})
        workflow.add_edge("detail_fix_plan", END)

        compiled_flow = workflow.compile()
        return compiled_flow

    def run(self) -> FixRefactoringPlan:
        compiled_flow = self.compile()
        messages = compiled_flow.invoke({'messages': [
            self.generation_system_message,
            HumanMessage(f"{self.source_file_path}: \n{self.source_code}")
        ]})
        return self._ref_plan

