[tool.poetry]
name = "refagent"
version = "0.1.0"
description = "An AI-agent which suggests refactoring changes to improve code quality"
authors = ["Abhiram98 <bellur.abhiram@gmail.com>"]
readme = "README.md"

#dependencies = [
#    "langchain",
#    "langchain-openai",
#    "langchain-ollama",
#    "langgraph",
#    "grazie_api_gateway_client @ https://packages.jetbrains.team/pypi/p/grazi/jetbrains-ai-platform-public/download/grazie-api-gateway-client/0.1.9/grazie_api_gateway_client-0.1.9-py3-none-any.whl",
#    "dotenv",
#    "pydantic",
#    "gitpython"
#]

[tool.poetry.dependencies]
python = "^3.9"
langchain = "*"
langchain-community = "*"
langchain-openai = "*"
langchain-ollama = "*"
langgraph = "*"
langsmith = "*"
grazie_api_gateway_client = { url = "https://packages.jetbrains.team/pypi/p/grazi/jetbrains-ai-platform-public/download/grazie-api-gateway-client/0.1.9/grazie_api_gateway_client-0.1.9.tar.gz" }
python-dotenv= "1.0.1"
pydantic = "*"
gitpython = "*"
PyGithub = "*"
pytest = "*"
pytest-mock = "*"


[[tool.poetry.source]]
name = "space-ai-agents"
url = "https://packages.jetbrains.team/pypi/p/ml-4-se-lab/ai-agents/simple"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
